/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libtsk.h>
#include <assert.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/* Header for class bindings_Sleuthkit__ */

#ifndef _Included_bindings_Sleuthkit__
#define _Included_bindings_Sleuthkit__
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     bindings_Sleuthkit__
 * Method:    openImgNat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jlong JNICALL Java_bindings_Sleuthkit_00024_openImgNat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    getImgSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_bindings_Sleuthkit_00024_getImgSize(JNIEnv * , jobject , jlong);
/*
 * Class:     bindings_Sleuthkit__
 * Method:    openFsNat
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL
Java_bindings_Sleuthkit_00024_openFsNat(JNIEnv *, jobject, jlong);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    getDirFilesNat
 * Signature: (JLjava/lang/String;)[Lpl/dyskobol/model/File;
 */
JNIEXPORT jobjectArray JNICALL
Java_bindings_Sleuthkit_00024_getDirFilesNat(JNIEnv*, jobject, jlong, jstring);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    getDirFilesByInodeNat
 * Signature: (JJ)[Lpl/dyskobol/model/File;
 */
JNIEXPORT jobjectArray JNICALL
Java_bindings_Sleuthkit_00024_getDirFilesByInodeNat(JNIEnv*, jclass, jlong, jlong);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    getFileInode
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL
Java_bindings_Sleuthkit_00024_getFileInode(JNIEnv*, jclass, jlong, jstring);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    openFileNat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL
Java_bindings_Sleuthkit_00024_openFileNat(JNIEnv*, jclass, jlong, jlong);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    closeFileNat
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_bindings_Sleuthkit_00024_closeFileNat(JNIEnv*, jclass, jlong);
/*
 * Class:     bindings_Sleuthkit__
 * Method:    readNat
 * Signature: (JJJ)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_bindings_Sleuthkit_00024_readNat(JNIEnv*, jclass, jlong, jlong, jlong);

/*
 * Class:     bindings_Sleuthkit__
 * Method:    readToBufferNat
 * Signature: (JJJ[BJ)J
 */
JNIEXPORT jlong JNICALL
Java_bindings_Sleuthkit_00024_readToBufferNat(JNIEnv*, jclass, jlong, jlong, jlong, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
