/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <libtsk.h>
#include <assert.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>


/* Header for class simple_Library__ */

#ifndef _Included_simple_Library__
#define _Included_simple_Library__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     simple_Library__
 * Method:    say
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_simple_Library_00024_say
  (JNIEnv *, jobject, jstring);

/*
 * Class:     simple_Library__
 * Method:    openImgNat
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT jlong JNICALL Java_simple_Library_00024_openImgNat
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
